Rewritten

diff --git a/linkalisation b/linkalisation
--- a/linkalisation
+++ b/linkalisation
@@ -1,109 +1,99 @@
 #!/bin/bash
 
-# this is to gracefully stop execution if there's non-zero error that
-# wasn't checked by an conditional statement. doesn't catch subshells
-# errors though.
 #set -e
 
-usage() {
-  echo "This script can link and unlink files in source directory to target directory";
-  echo "that has the same structure."
-  echo "The script also renames existing files and directories to filename~bak before linking.";
-  echo "	Usage: $0 -s SOURCE -t TARGET | -u -t TARGET" 1>&2
+show_usage() {
+	cat <<- USAGE >&2
+		Creates symbolic links to files in the source directory from the target directory, recursively,
+		but only if a file exists in the target directory with the same name.
+		Before a link is created, the existing namesake file in the target is suffixed with '.upstream'
+		Both directores must have the same structure. I.e source and target files must have the same path
+		relative to source and target, as roots.
+		Usage:
+			$(basename $0) [-f] -s SOURCE -t TARGET | -r TARGET
+		
+		Where:
+			-f	Force replacement of existing symlinks.
+			-r	Remove links and restore .upstream files to their original names.
+USAGE
+	exit 85
 }
 
-exit_abnormal() {
-  usage
-  exit 1
+if [ -z $# ]; then
+	show_usage
+fi
+
+check_path() {
+	typeset -n root=$1
+	root=$(readlink -e "$2")/
+	if [ $? -ne 0 ]; then
+		echo "Directory ./$2 doesn't exist. Exiting."
+		exit 1
+	fi
 }
 
-exit_with_error() {
-  echo "$1"
-  exit 1
-}
-
-validate_dir() {
-  [ -d $1 ] ||
-    exit_with_error "The path: $1 doesn't exist or isn't a directory."
-  [ -r $1 ] ||
-    exit_with_error "The path: $1 is not readable."
-  [ -w $1 ] ||
-    exit_with_error "The path: $1 is not writable."
-  [ -x $1 ] ||
-    exit_with_error "The path: $1 is not exeutable."
-  $(test $(ls -1 $1 | wc -l) -eq 0) &&
-    exit_with_error "$1 is empty!"
-}
-
-get_path_part() {
-  str=$1
-  delimiter=$2
-  s=$str$delimiter
-  array=();
-  while [[ $s ]]; do
-    array+=( "${s%%"$delimiter"*}" );
-    s=${s#*"$delimiter"};
-  done;
-  echo ${array[1]}
-}
-
-link() {
-  local source=$(readlink -f "$1")
-  local destination=$(readlink -f "$2")
-  for fPath in $(find "$source" -type f,l);
-  do
-    pathPart=$(get_path_part $fPath $source)
-    linkPath="$destination$pathPart"
-    linkPathDir=$(dirname $linkPath)
-    filename=$(basename $pathPart)
-    [ -e $linkPath -a ! -L $linkPath ] && mv "$linkPath" "$linkPath~bak";
-    [ ! -e $linkPathDir ] && mkdir -p $linkPathDir
-    $(cd "$linkPathDir" && ln -sf "$linkPath" $filename)
-    echo "linked $linkPath"
-  done
-}
-
-unlink() {
-  local destination=$(readlink -f $1)
-
-  # TODO: unlink only the links created by this script.
-  # not other links that was already there in destination
-  # before running this script.
-  find "$destination" -type l -exec unlink {} \;
-
-  for fPath in $(find $destination -type f);
-  do 
-    echo $fPath | grep -qP "~bak$" &&
-	    mv "$fPath" "$(echo ${fPath:0:${#fPath}-4})"
-  done
-}
-
-while getopts :s:t:u option
-do
-  case "${option}"
-    in
-      s) source=${OPTARG}
-	 ;;
-      t) destination=${OPTARG}
-	 ;;
-      u) unLnk=1
-         ;;
-      :) echo "Error: -${OPTARG} requires an argument."
-	 exit_abnormal
-	 ;;
-      *) exit_abnormal
-	 ;;
+while [ $# -gt 0 ]; do
+case "$1" in
+	-s|--source)
+		check_path sRoot $2
+		shift
+	;;
+	-t|--target)
+		check_path tRoot $2
+		shift
+	;;
+	-r|--restore)
+		check_path rRoot $2
+		shift
+	;;
+	-f|--force)
+		FORCE_LINKS=true
+	;;
+	-h|--help)
+		show_usage
+	;;
+	*)
+		show_usage
   esac
+  shift
 done
 
-
-if [ -z "$source" -a ! -z "$destination" -a ! -z "$unLnk" ]; then
-  validate_dir $destination
-  unlink $destination && echo "restored backup and unlinked files and directories."
+if [ -z "$sRoot" -a -z "$tRoot" -a ! -z "$rRoot" ]; then
+	echo -e "Restoring upstream files at $rRoot\n" >&2
+	c=0
+	for rFile in $(find -H "$rRoot" -name "*.upstream" -type f);
+	do
+		oFile=${rFile%.upstream}
+		if [ -h $oFile ]; then
+			rm "$oFile"
+		fi
+		mv "$rFile" "$oFile" 
+		echo "Restored ./${oFile#$rRoot}" >&2
+		let c=c+1
+	done
+	echo -e "\nDone restoring $c files." >&2
+	exit 0
+elif [ ! -z "$sRoot" -a ! -z "$tRoot" -a -z "$rRoot" ]; then
+	echo -e "Linking translation files\nfrom: $sRoot\nto:   $tRoot\n" >&2
+	c=0
+	for sFile in $(find -H "$sRoot" -type f);
+	do
+		linkT=${sFile/#$sRoot/$tRoot}
+		if [ -f $linkT ]; then
+			if ! mv --no-clobber "$linkT" "$linkT.upstream"; then
+				echo "Skipping $sFile: Target could not be backed up." >&2
+			else
+				if ln --symbolic ${FORCE_LINKS+--force} "$sFile" "$linkT"; then
+					echo "Done ${FORCE_LINKS+forced} linking ./${linkT#$tRoot}" >&2
+					let c=c+1
+				fi
+			fi
+		else
+			echo "Skipping ./${sFile#$sRoot}: doesn't exist in target directory." >&2
+		fi
+	done
+	echo -e "\nDone linking $c files." >&2
+	exit 0
 fi
-if [ ! -z "$source" -a ! -z "$destination" -a -z "$unLnk" ]; then
-  validate_dir $source
-  validate_dir $destination
-  link $source $destination && echo "made backup and linked source files and directories to target"
-fi
 
+show_usage
